use enum_iterator::Sequence;

#[derive(Debug, Sequence, Clone, Copy)]
pub enum PokemonType {
    Normal,
    Fighting,
    Flying,
    Poison,
    Ground,
    Rock,
    Bug,
    Ghost,
    Steel,
    Fire,
    Water,
    Grass,
    Electric,
    Psychic,
    Ice,
    Dragon,
    Dark,
    Fairy,
}

use PokemonType::*;
impl PokemonType {
    pub fn get_color(&self) -> (u8, u8, u8) {
        match *self {
            Normal => (170, 170, 153),
            Fire => (255, 68, 34),
            Water => (51, 153, 255),
            Electric => (255, 204, 51),
            Grass => (119, 204, 85),
            Ice => (102, 204, 255),
            Fighting => (187, 85, 68),
            Poison => (170, 85, 153),
            Ground => (221, 187, 85),
            Flying => (136, 153, 255),
            Psychic => (255, 85, 153),
            Bug => (170, 187, 34),
            Rock => (187, 170, 102),
            Ghost => (102, 102, 187),
            Dragon => (119, 102, 238),
            Dark => (119, 85, 68),
            Steel => (170, 170, 187),
            Fairy => (238, 153, 238),
        }
    }

    pub fn get_damage_multiplier(attacker: &Self, defender: &Self) -> f64 {
        match (attacker, defender) {
            (Normal, Rock) => 0.5,
            (Normal, Ghost) => 0.0,
            (Normal, Steel) => 0.5,
            (Normal, _) => 1.0,

            (Fire, Fire) => 0.5,
            (Fire, Water) => 0.5,
            (Fire, Grass) => 2.0,
            (Fire, Ice) => 2.0,
            (Fire, Bug) => 2.0,
            (Fire, Rock) => 0.5,
            (Fire, Dragon) => 0.5,
            (Fire, Steel) => 2.0,
            (Fire, _) => 1.0,

            (Water, Fire) => 2.0,
            (Water, Water) => 0.5,
            (Water, Grass) => 0.5,
            (Water, Ground) => 2.0,
            (Water, Rock) => 2.0,
            (Water, Dragon) => 0.5,
            (Water, _) => 1.0,

            (Electric, Water) => 0.5,
            (Electric, Electric) => 0.5,
            (Electric, Grass) => 0.5,
            (Electric, Ground) => 0.0,
            (Electric, Flying) => 2.0,
            (Electric, Dragon) => 0.5,
            (Electric, _) => 1.0,

            (Grass, Fire) => 0.5,
            (Grass, Water) => 2.0,
            (Grass, Grass) => 0.5,
            (Grass, Poison) => 0.5,
            (Grass, Ground) => 2.0,
            (Grass, Flying) => 0.5,
            (Grass, Bug) => 0.5,
            (Grass, Rock) => 2.0,
            (Grass, Dragon) => 0.5,
            (Grass, _) => 1.0,

            (Ice, Fire) => 0.5,
            (Ice, Water) => 0.5,
            (Ice, Grass) => 2.0,
            (Ice, Ice) => 0.5,
            (Ice, Ground) => 2.0,
            (Ice, Flying) => 2.0,
            (Ice, Dragon) => 2.0,
            (Ice, Steel) => 0.5,
            (Ice, _) => 1.0,

            (Fighting, Normal) => 2.0,
            (Fighting, Ice) => 2.0,
            (Fighting, Poison) => 0.5,
            (Fighting, Flying) => 0.5,
            (Fighting, Psychic) => 0.5,
            (Fighting, Bug) => 0.5,
            (Fighting, Rock) => 2.0,
            (Fighting, Ghost) => 0.0,
            (Fighting, Dark) => 2.0,
            (Fighting, Steel) => 2.0,
            (Fighting, Fairy) => 0.5,
            (Fighting, _) => 1.0,

            (Poison, Grass) => 2.0,
            (Poison, Poison) => 0.5,
            (Poison, Ground) => 0.5,
            (Poison, Rock) => 0.5,
            (Poison, Ghost) => 0.5,
            (Poison, Steel) => 0.0,
            (Poison, Fairy) => 2.0,
            (Poison, _) => 1.0,

            (Ground, Fire) => 2.0,
            (Ground, Electric) => 2.0,
            (Ground, Grass) => 0.5,
            (Ground, Poison) => 2.0,
            (Ground, Flying) => 0.0,
            (Ground, Bug) => 0.5,
            (Ground, Rock) => 2.0,
            (Ground, Steel) => 2.0,
            (Ground, _) => 1.0,

            (Flying, Electric) => 0.5,
            (Flying, Grass) => 2.0,
            (Flying, Fighting) => 2.0,
            (Flying, Bug) => 2.0,
            (Flying, Rock) => 0.5,
            (Flying, Steel) => 0.5,
            (Flying, _) => 1.0,

            (Psychic, Fighting) => 2.0,
            (Psychic, Poison) => 2.0,
            (Psychic, Psychic) => 0.5,
            (Psychic, Dark) => 0.0,
            (Psychic, Steel) => 0.5,
            (Psychic, _) => 1.0,

            (Bug, Fire) => 0.5,
            (Bug, Grass) => 2.0,
            (Bug, Fighting) => 0.5,
            (Bug, Poison) => 0.5,
            (Bug, Flying) => 0.5,
            (Bug, Psychic) => 2.0,
            (Bug, Ghost) => 0.5,
            (Bug, Dark) => 2.0,
            (Bug, Steel) => 0.5,
            (Bug, Fairy) => 0.5,
            (Bug, _) => 1.0,

            (Rock, Fire) => 2.0,
            (Rock, Ice) => 2.0,
            (Rock, Fighting) => 0.5,
            (Rock, Ground) => 0.5,
            (Rock, Flying) => 2.0,
            (Rock, Bug) => 2.0,
            (Rock, Steel) => 0.5,
            (Rock, _) => 1.0,

            (Ghost, Normal) => 0.0,
            (Ghost, Psychic) => 2.0,
            (Ghost, Ghost) => 2.0,
            (Ghost, Dark) => 0.5,
            (Ghost, _) => 1.0,

            (Dragon, Dragon) => 2.0,
            (Dragon, Steel) => 0.5,
            (Dragon, Fairy) => 0.0,
            (Dragon, _) => 1.0,

            (Dark, Fighting) => 0.5,
            (Dark, Psychic) => 2.0,
            (Dark, Ghost) => 2.0,
            (Dark, Dark) => 0.5,
            (Dark, Fairy) => 0.5,
            (Dark, _) => 0.0,

            (Steel, Fire) => 0.5,
            (Steel, Water) => 0.5,
            (Steel, Electric) => 0.5,
            (Steel, Ice) => 2.0,
            (Steel, Rock) => 2.0,
            (Steel, Steel) => 0.5,
            (Steel, Fairy) => 2.0,
            (Steel, _) => 0.0,

            (Fairy, Fire) => 0.5,
            (Fairy, Fighting) => 2.0,
            (Fairy, Poison) => 0.5,
            (Fairy, Dragon) => 2.0,
            (Fairy, Dark) => 2.0,
            (Fairy, Steel) => 0.5,
            (Fairy, _) => 1.0,
        }
    }
}
